### ISSUE TITLE
Confusing comment in e_type_min_max/e_util_type_min_max.e

### ISSUE THREAD

**Issue by cmarqu** [efratcdn/e_type_min_max#1]
Hi Efrat,

in ``e_type_min_max/e_util_type_min_max.e``, you have both
> define as, the better implementation when the type are numeric

and

> define as computed, the better implementation when the type is numeric

There is a "not" missing in one of them I suppose?

**Comment by efratcdn** [comment]
thanks for the catch! 

The DAC (define as computed) is the better implementation  for numeric, and define-as - for all other types.

I will fix the code file

**Comment by cmarqu** [comment]
Thanks, the comments are well understandable now.
